import { text } from "./constants.js";

document.getElementById("send-email-btn").addEventListener("click", (event) => {
  event.preventDefault();
  sendMail().then((response) => {
    if (response.success) {
      alert("Успешно изпратихте поканата!");
    }
  });
});

async function sendMail() {
  const manualCanvas = document.getElementById("meme");
  const autoCanvas = document.getElementById("autogenerated-meme");
  const canvas = autoCanvas.innerHTML ? autoCanvas : manualCanvas;

  const dataURL = canvas.toDataURL("image/png");
  const base64image = dataURL.replace(/^data:image\/(png|jpg);base64,/, "");

  const mailData = {
    message: generateText(),
    invitation: base64image,
  };

  const response = await fetch("../../backend/endpoints/mails.php", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(mailData),
  });

  const result = await response.json();

  return result;
}

function generateText() {
  const { theme, presentationDate, presentationTime, facultyNumber } =
    getFormData();

  // return `Здравейте! Каня ви на презентацията на ${user.first_name} ${user.last_name} с ФН: ${facultyNumber} на ${presentationDate} от ${presentationTime} на тема ${theme}`;
  return text;
}

function getFormData() {
  return {
    theme: document.getElementById("theme").value,
    presentationDate: document.getElementById("presentation-date").value,
    presentationTime: document.getElementById("presentation-time").value,
    facultyNumber: document.getElementById("faculty-number").value,
    description: document.getElementById("description").value,
  };
}
